run_name: test-trash
ga_schedule:
- - 0
  - 350000
- - 5000
  - 700000
- - 10000
  - 1500000
B: 6
T: 2048
max_steps: 200000
eval_iters: 2
val_step: 100
save_step: 500
data_type: bf16
FSDP_param_dtype: bf16
FSDP_reduce_dtype: bf16
FSDP_buffer_dtype: bf16
reshard_after_forward: false
resume_training: false
resume_step: 20
resume_data_reset: continue
clip_warmup: 1.0
clip_standard: 1.0
tok_kind: llama
tok_path: ../tokenizers/llama_tokenizer
special_tokens: ../../notebooks/datasets/tokenized/llama/tokenizer_config.json
use_keel: true
keel_alpha: 200
cfg_layers: 72
cfg_heads: 14
cfg_kv_heads: 14
cfg_embd: 1344
cfg_intermediate: 2240
multiple_of: 128
norm_eps: 1.0e-05
dropout: 0.0
use_activation_checkpointing: true
qk_norm_mode: before_rope
tie_word_embeddings: false
rope_theta: 500000.0
compile_model: true
compile_mode: default
lr_schedule_type: plateau
max_lr: 0.0045
min_lr: 4.5e-05
warmup_steps: 1500
decay_to_first_plat_pct: 0.08
first_plat_lr: 0.0005
first_plat_len_pct: 0.5
decay_to_second_pct: 0.1
second_plat_lr: 0.0002
second_plat_len_pct: 0.2
optimizer_type: adamc_8bit
beta1: 0.9
beta2: 0.95
weight_decay: 0.03
data_root_path: ../../notebooks/datasets/tokenized/llama/
groups:
- - stories
  - 100.0
#- - ao3
#  - 22.0
#- - books
#  - 22.0
#- - edufineweb_10BT
#  - 15.0
#- - preselect
#  - 10.0
#- - mid_smoltalk
#  - 8.0
#- - mid_mmlu
#  - 1.0
gen_log_file: gen_log.txt
train_log_file: train_log.txt
val_log_file: val_log.txt
server_port: 8888
nas_root: ../ckpt/mara_fsdp2/
local_checkpoint_root: ~/checkpoints/
nas_path: ../ckpt/mara_fsdp2/mf2-adam/
local_checkpoint_dir: /home/josef/checkpoints/mf2-adam
total_batch_size: 1462272
cfg_voc_sz: 32768
